### PR TITLE
MD5 integrity check

### PR DESCRIPTION
**Pull request by pankkor**

### CODE REVIEW

**Comment by pankkor** [comment]
@lmirosevic please note this is optional 5c89048. When a class has category method name collisions it's undefined which implementation will be used and it's undesirable. GBToolbox defines `-map:` as well as GBCloudBox.
I think it's better to move the code in a static function for GBCloudBox to avoid name collision.

**Comment by lmirosevic** [comment]
Good call on the map, and on making the throw optional. But GBToolbox already implements md5 as a category on nsdata I believe, so introducing it as a dependency would be ok I think, then we can use the array map from there. 

Also, please implement the throw option as a property, instead of a preprocessor macro. Macros are dirty.

**Comment by pankkor** [comment]
@lmirosevic I really think that libs should take as less dependencies ad possible. GBToolbox is a big lib comparing to GBCloudBox and I would like to avoid adding it as a dependency. `MD5` is a trivial call to a C lib and `map` is just a syntax sugar which is used in one place and this code can be written without `map`. Those who use GBCloudbox without GBToolbox would be happy not to get GBToolbox as a dependency

**Comment by pankkor** [comment]
> Also, please implement the throw option as a property, instead of a preprocessor macro. Macros are dirty.

done

**Comment by pankkor** [comment]
@lmirosevic can you review it when you have time please

**Pull request merged**
